<a href="https://colab.research.google.com/github/MrPavalion/basic/blob/kits/datapreprocessing_template_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Step 1: Import Data

In [30]:
#step 1 we have to import the data from csv file 
#pip install pandas
import pandas as pd
data =  pd.read_csv("Salary_Data_SLR.csv")
data.head()


YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [31]:
data


YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

#STEP 2:SEPERATE THE I/P &O/P

In [32]:
#step-2: Now we have to seperate the both input and output varibles
#Independent Varables
X = data.iloc[:,0].values
X = X.reshape(-1,1)
Y=data.iloc[:,-1].values


In [33]:
X


array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [34]:
Y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])


# STEP 3:TRAIN THE I/P & O/P



In [35]:
from sklearn.model_selection import train_test_split
X_train ,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2)


In [36]:
X_test

array([[3.2],
       [5.1],
       [2. ],
       [4. ],
       [5.3],
       [9. ]])

In [37]:
Y_test

array([ 54445.,  66029.,  43525.,  56957.,  83088., 105582.])

#STEP 4: MODEL

In [39]:

#y=mx+c
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [42]:
regressor.coef_


array([9448.72911518])

In [44]:
regressor.intercept_


26440.426322293635

#STEP 5: PREDICTION

In [46]:
regressor.predict(X_test)

array([ 56676.35949086,  74628.94480969,  45337.88455264,  64235.342783  ,
        76518.69063272, 111478.98835887])

In [48]:
Y_test

array([ 54445.,  66029.,  43525.,  56957.,  83088., 105582.])